### PR TITLE
Fix lambda return types

### PR DESCRIPTION
**Pull request by hasufell**
This fixes compilation for strict compilers like clang.

### CODE REVIEW

**Comment by mhogomchungu** [comment]
will appreciate if you could post the warning/error you are getting when you are compiling.

**Comment by hasufell** [comment]
```
/var/tmp/paludis/app-crypt-zuluCrypt-4.7.5/work/zuluCrypt-4.7.5/zuluCrypt-gui/walletconfig.cpp:190:6: error: return type 'QByteArray' must match previous return type
      'const QByteArray' when lambda expression has unspecified explicit return type
                                        return ShouldNotGetHere ;
                                        ^
[...]
/var/tmp/paludis/app-crypt-zuluCrypt-4.7.5/work/zuluCrypt-4.7.5/zuluMount-gui/zulumounttask.cpp:322:4: error: return type 'const QString' must match previous return type
      'QString' when lambda expression has unspecified explicit return type
                        return dev ;
                        ^
/var/tmp/paludis/app-crypt-zuluCrypt-4.7.5/work/zuluCrypt-4.7.5/zuluMount-gui/zulumounttask.cpp:373:4: error: return type 'const QString' must match previous return type
      'QString' when lambda expression has unspecified explicit return type
                        return volume ;
                        ^
```

Those are just the errors. If you want to see the warnings, have a look at the whole build log (built with this patch): https://gist.github.com/hasufell/40ed7e048e7755a18a08

**Comment by hasufell** [comment]
On another node... would you be interested to add travis integration for this repository? It's pretty simple in fact, see
http://docs.travis-ci.com/user/getting-started/
https://github.com/nicklan/pnmixer/blob/master/.travis.yml (this yml file will build with both clang and gcc... it might make sense to add ```-Werror``` flag to those builds)

**Comment by mhogomchungu** [comment]
will look into it,thanks.

i now build with both gcc and clang so the cland specific build errors will no longer be there.

**Comment by mhogomchungu** [comment]
it doest work because their compiler is too old,the compiler they are using was reported as:
```
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
```
and the build process failed with the following error:
```
Scanning dependencies of target lxqtwallet

[ 31%] Building CXX object zuluCrypt-gui/lxqt_wallet/frontend/CMakeFiles/lxqtwallet.dir/changepassworddialog.cpp.o

cc1plus: error: unrecognized command line option ‘-std=c++11’

make[2]: *** [zuluCrypt-gui/lxqt_wallet/frontend/CMakeFiles/lxqtwallet.dir/changepassworddialog.cpp.o] Error 1

make[1]: *** [zuluCrypt-gui/lxqt_wallet/frontend/CMakeFiles/lxqtwallet.dir/all] Error 2

make: *** [all] Error 2
```

**Comment by mhogomchungu** [comment]
clang build failed too.

clang version they are using is:
```
clang version 3.4 (tags/RELEASE_34/final)
```
and the build failed with the following:
```
Scanning dependencies of target lxqtwallet

[ 31%] Building CXX object zuluCrypt-gui/lxqt_wallet/frontend/CMakeFiles/lxqtwallet.dir/changepassworddialog.cpp.o

clang: warning: argument unused during compilation: '-s'

In file included from /home/travis/build/mhogomchungu/zuluCrypt/zuluCrypt-gui/lxqt_wallet/frontend/changepassworddialog.cpp:31:

In file included from /home/travis/build/mhogomchungu/zuluCrypt/zuluCrypt-gui/lxqt_wallet/frontend/changepassworddialog.h:34:

In file included from /usr/include/qt4/QtGui/QDialog:1:

In file included from /usr/include/qt4/QtGui/qdialog.h:45:

In file included from /usr/include/qt4/QtGui/qwidget.h:49:

In file included from /usr/include/qt4/QtGui/qpalette.h:47:

In file included from /usr/include/qt4/QtGui/qbrush.h:53:

In file included from /usr/include/qt4/QtGui/qpixmap.h:49:

In file included from /usr/include/qt4/QtCore/qsharedpointer.h:50:

/usr/include/qt4/QtCore/qsharedpointer_impl.h:435:17: warning: 'register'

storage class specifier is deprecated [-Wdeprecated-register]

register int tmp = o->strongref;

^~~~~~~~~

/usr/include/qt4/QtCore/qsharedpointer_impl.h:595:43: warning: field 'd' is

uninitialized when used here [-Wuninitialized]

inline QWeakPointer(X *ptr) : d(ptr ? d->getAndRef(ptr) : 0), value(ptr)

^

/usr/include/qt4/QtCore/qsharedpointer_impl.h:822:5: warning: 'register' storage

class specifier is deprecated [-Wdeprecated-register]

register X *ptr = static_cast<X *>(src.data()); // if you get an err...

^~~~~~~~~

/usr/include/qt4/QtCore/qsharedpointer_impl.h:834:5: warning: 'register' storage

class specifier is deprecated [-Wdeprecated-register]

register X *ptr = dynamic_cast<X *>(src.data()); // if you get an er...

^~~~~~~~~

/usr/include/qt4/QtCore/qsharedpointer_impl.h:846:5: warning: 'register' storage

class specifier is deprecated [-Wdeprecated-register]

register X *ptr = const_cast<X *>(src.data()); // if you get an erro...

^~~~~~~~~

/usr/include/qt4/QtCore/qsharedpointer_impl.h:866:5: warning: 'register' storage

class specifier is deprecated [-Wdeprecated-register]

register X *ptr = qobject_cast<X *>(src.data());

^~~~~~~~~

In file included from /home/travis/build/mhogomchungu/zuluCrypt/zuluCrypt-gui/lxqt_wallet/frontend/changepassworddialog.cpp:31:

In file included from /home/travis/build/mhogomchungu/zuluCrypt/zuluCrypt-gui/lxqt_wallet/frontend/changepassworddialog.h:36:

In file included from /usr/include/qt4/QtCore/QDebug:1:

In file included from /usr/include/qt4/QtCore/qdebug.h:50:

In file included from /usr/include/qt4/QtCore/qtextstream.h:48:

In file included from /usr/include/qt4/QtCore/qlocale.h:45:

In file included from /usr/include/qt4/QtCore/qvariant.h:48:

/usr/include/qt4/QtCore/qmetatype.h:256:5: warning: 'register' storage class

specifier is deprecated [-Wdeprecated-register]

register int id = qMetaTypeId<T>();

^~~~~~~~~

In file included from /home/travis/build/mhogomchungu/zuluCrypt/zuluCrypt-gui/lxqt_wallet/frontend/changepassworddialog.cpp:31:

In file included from /home/travis/build/mhogomchungu/zuluCrypt/zuluCrypt-gui/lxqt_wallet/frontend/changepassworddialog.h:42:

In file included from /home/travis/build/mhogomchungu/zuluCrypt/zuluCrypt-gui/lxqt_wallet/frontend/task.h:35:

In file included from /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/future:40:

In file included from /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/mutex:40:

/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/chrono:535:6: error:

no matching constructor for initialization of 'duration' (aka

'std::chrono::duration<long, std::ratio<1, 1000000> >')

: __d(__t.time_since_epoch())

^ ~~~~~~~~~~~~~~~~~~~~~~

/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/condition_variable:106:42: note:

in instantiation of function template specialization

'std::chrono::time_point<std::chrono::system_clock,

std::chrono::duration<long, std::ratio<1, 1000000> >

>::time_point<std::chrono::duration<long, std::ratio<1, 1000000000> > >'

requested here

const __clock_t::time_point __s_atime = __s_entry + __delta;

^

/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/chrono:234:12: note:

candidate constructor not viable: no known conversion from

'duration<[...], ratio<[...], 1000000000>>' to 'const duration<[...],

ratio<[...], 1000000>>' for 1st argument

constexpr duration(const duration&) = default;

^

/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/chrono:237:19: note:

candidate template ignored: disabled by 'enable_if' [with _Rep2 =

std::chrono::duration<long, std::ratio<1, 1000000000> >]

enable_if<is_convertible<_Rep2, rep>::value

^

/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/chrono:244:19: note:

candidate template ignored: disabled by 'enable_if' [with _Rep2 = long,

_Period2 = std::ratio<1, 1000000000>]

enable_if<treat_as_floating_point<rep>::value

^

/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/chrono:232:12: note:

candidate constructor not viable: requires 0 arguments, but 1 was provided

constexpr duration() : __r() { }

^

7 warnings and 1 error generated.

make[2]: *** [zuluCrypt-gui/lxqt_wallet/frontend/CMakeFiles/lxqtwallet.dir/changepassworddialog.cpp.o] Error 1

make[1]: *** [zuluCrypt-gui/lxqt_wallet/frontend/CMakeFiles/lxqtwallet.dir/all] Error 2

make: *** [all] Error 2

The command "cmake -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=lib/$(DEB_HOST_MULTIARCH) -DCMAKE_BUILD_TYPE=release . && make" exited with 2.
```

**Comment by hasufell** [comment]
https://stackoverflow.com/questions/22111549/travis-ci-with-clang-3-4-and-c11

there seems to be a suggestion on how to upgrade to gcc-4.8 and also have a proper clang with c++11 support

**Comment by mhogomchungu** [comment]
it failed again with the same result probably because my changes[0] made no difference for some reason and the build process continued to use outdated compilers,will revisit this service later on.

what makes this travis service better compared to open suse build service?

open suse build service seems to be better since i can build using multiple distributions[1] and they also offer hosting of build packages[2][3]

[0] https://github.com/mhogomchungu/zuluCrypt/blob/3a8dd10a64179ec712fbde700a33e36097ac1657/.travis.yml

[1] https://build.opensuse.org/project/show?project=home%3Amhogomchungu

[2] http://software.opensuse.org/download.html?project=home%3Amhogomchungu&package=zuluCrypt

[3] http://download.opensuse.org/repositories/home:/mhogomchungu/

**Comment by hasufell** [comment]
I guess opensuse build service is fine too. The cool thing about travis is just that its very tightly connected with github and runs automatically on every push AND pull request (that's the cool part), has a nice icon showing the build status and so on.

**Comment by mhogomchungu** [comment]
it now works with gcc compiler as i have managed to update the compiler to gcc 4.8.

clang still fails and i think it needs atleast version 3.5 while the ppa has 3.4.2 as the latest.

you can look at build histories from here: https://travis-ci.org/mhogomchungu/zuluCrypt/builds

**Comment by hasufell** [comment]
Nice.

Usually people also add a link/icon to the build status in the README.
```
[![Build Status](https://api.travis-ci.org/mhogomchungu/zuluCrypt.svg?branch=master)](https://travis-ci.org/mhogomchungu/zuluCrypt)
```

looks like this: [Build Status](https://travis-ci.org/mhogomchungu/zuluCrypt)

**Pull request merged**
