### PR TITLE
CMAKE: use GNUInstallDirs

### PR DESCRIPTION
**Pull request by hasufell**
This fixes various problems of misplaced files in
distributions that have a non-standard filesystem
layout.

### CODE REVIEW

**Comment by mhogomchungu** [comment]
Your changes removes "LIB_SUFFIX" variable and i think you should return it since a lot of distributions like arch uses it to customize library destination path.

Debian packages for example build with "-DLIB_SUFFIX=lib/$(DEB_HOST_MULTIARCH)" and i do not think your solution accounts for path changes in debian/ubuntu and other debian based systems.

I just tested your changes on 64 bit arch linux and it uses "/usr/lib64" library destination path while this path is invalid in arch as it requires the path to be "/usr/lib".

Can you add back support for "LIB_SUFFIX" variable?

**Comment by hasufell** [comment]
> Can you add back support for "LIB_SUFFIX" variable?

There's no use for it, since you can control all paths properly now. Use `-CMAKE_INSTALL_LIBDIR` instead.

**Comment by mhogomchungu** [comment]
your changes breaks previously working build systems and this is the reason i would like to continue supporting the variable.The variable is widely used and it does not seem appropriate to just drop it.

Somebody trying to build zuluCrypt from git in arch linux right now will see the following error:

```
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) zulucrypt-git-4.9.0.2.g12e805d-1

Total Installed Size:  5.19 MiB
Net Upgrade Size:      0.02 MiB

checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
zulucrypt-git: /usr/lib64 exists in filesystem
zulucrypt-git: /usr/lib64/libzuluCrypt-exe.so exists in filesystem
zulucrypt-git: /usr/lib64/libzuluCrypt-exe.so.1.2.0 exists in filesystem
zulucrypt-git: /usr/lib64/libzuluCrypt.so exists in filesystem
zulucrypt-git: /usr/lib64/libzuluCrypt.so.1.2.0 exists in filesystem
zulucrypt-git: /usr/lib64/libzuluCryptPluginManager.so exists in filesystem
zulucrypt-git: /usr/lib64/libzuluCryptPluginManager.so.1.0.0 exists in filesystem
zulucrypt-git: /usr/lib64/pkgconfig/libzuluCrypt.pc exists in filesystem
zulucrypt-git: /usr/lib64/zuluCrypt/generic_header exists in filesystem
zulucrypt-git: /usr/lib64/zuluCrypt/gpg exists in filesystem
zulucrypt-git: /usr/lib64/zuluCrypt/hmac exists in filesystem
zulucrypt-git: /usr/lib64/zuluCrypt/keydialog-qt exists in filesystem
zulucrypt-git: /usr/lib64/zuluCrypt/keykeyfile exists in filesystem
zulucrypt-git: /usr/lib64/zuluCrypt/keyring exists in filesystem
zulucrypt-git: /usr/lib64/zuluCrypt/luks exists in filesystem
zulucrypt-git: /usr/lib64/zuluCrypt/steghide exists in filesystem
zulucrypt-git: /usr/lib64/zuluCrypt/tomb exists in filesystem
zulucrypt-git: /usr/lib64/zuluCrypt/zuluCrypt-testKey exists in filesystem
Errors occurred, no packages were upgraded.

```

**Comment by hasufell** [comment]
> your changes breaks previously working build systems and this is the reason i would like to continue supporting the variable.

Update the documentation and tell them to use `-DCMAKE_INSTALL_LIBDIR=lib` instead. What's the problem? The use of custom variables like `LIB_SUFFIX` is not widely used. GNUInstallDirs is widely used.

**Comment by mhogomchungu** [comment]
Will update documentation and tell people to start using ```-DCMAKE_INSTALL_LIBDIR=``` variable.

Will also readd support for ```LIB_SUFFIX```  because i do not want to break working build systems and as far as i know,"everybody uses it".

arch linux uses it: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=zulucrypt

slackware uses it: https://github.com/conraid/SlackBuilds/blob/master/zulucrypt/zulucrypt.SlackBuild

debian uses it: https://github.com/marciosouza20/zulucrypt/blob/master/rules

should i continue?

**Comment by hasufell** [comment]
Packagers don't need handholding. They are supposed to know about such things and adapt to changes.

**Pull request merged**
